# permissions for end users to view appdeployers.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: appdeployer-viewer-role
rules:
- apiGroups:
  - deploy.jiang.operator
  resources:
  - appdeployers
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - deploy.jiang.operator
  resources:
  - appdeployers/status
  verbs:
  - get
