apiVersion: deploy.jiang.operator/v1
kind: AppDeployer
metadata:
  name: appdeployer-sample
spec:
  # TODO(user): Add fields here
  size: 1 # pod副本
  containers:
    - name: c1
      image: busybox:1.34
      command:
        - "sleep"
        - "3600"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      volumeMounts:
        - name: appdeployer-sample # 限定与AppDeployer自己的名字相同，不然会报错。
          mountPath: /etc/config # 可自由修改
    - name: c2
      image: busybox:1.34
      command:
        - "sleep"
        - "3600"
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
  service: true   # 自定义是否要配置Service
  service_type: NodePort # 目前支持NodePort ClusterIP 转换，注意：如果使用ClusterIP nodePort端口字段必须删除，否则会报错。
  ports:  #端口
    - port: 80
      targetPort: 80 # 容器端口
      nodePort: 30002 #service端口  注意：如果使用ClusterIP nodePort端口字段必须删除，否则会报错。
  # 支持configmap 挂载给pod，并实现自动热更新
  configmap: true

configmap_data:
  data:
    player_initial_lives: "3"
    ui_properties_file_name: "user-interface.properties"

